import streamlit as st
import pandas as pd
import time
from datetime import datetime
import os
import base64
import plotly.graph_objects as go

# --- 1. UI CONFIGURATION & THEME ---
st.set_page_config(page_title="REAP-2026 Eligibility Simulator", page_icon="🏛️", layout="wide")


def get_base64_of_bin_file(bin_file):
    if os.path.exists(bin_file):
        with open(bin_file, 'rb') as f:
            data = f.read()
        return base64.b64encode(data).decode()
    return ""


logo_base64 = get_base64_of_bin_file("CEGLogo.png")
logo_html = f'<img src="data:image/png;base64,{logo_base64}" class="header-logo">' if logo_base64 else ''

# Official Header CSS 
st.markdown(f"""
<style>
    .official-header {{
        background: linear-gradient(135deg, #112240 0%, #0A192F 100%);
        padding: 20px 30px;
        border-radius: 12px;
        border-bottom: 4px solid #D4AF37; 
        display: flex;
        align-items: center; 
        justify-content: flex-start; 
        margin-bottom: 20px;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.4);
    }}
    .header-logo {{ height: 100px; margin-right: 30px; }}
    .header-text {{ display: flex; flex-direction: column; justify-content: center; }}
    .header-text h1 {{ font-family: 'Georgia', serif; font-weight: 800; margin: 0; margin-bottom: 5px; font-size: 2.6rem; color: #FFFFFF; line-height: 1.1; }}
    .header-text p {{ margin: 0; font-size: 1.1rem; letter-spacing: 1px; color: #e2e8f0; }}
    .highlight {{ color: #D4AF37; }}

    .stButton > button[kind="secondary"]:hover {{
        border-color: #EF4444; 
        color: #EF4444; 
    }}
</style>
<div class="official-header">
    {logo_html}
    <div class="header-text">
        <h1>REAP <span class="highlight">2026</span></h1>
        <p>CENTRALIZED ADMISSION PROCESS • ELIGIBILITY SIMULATOR</p>
    </div>
</div>
""", unsafe_allow_html=True)

st.warning(
    "**OFFICIAL DISCLAIMER:** This Eligibility Simulator is provided for informational and guidance purposes only. The projected priority tiers, effective scores, and ranking lists generated by this tool are tentative and based entirely on the unverified data entered by the user. The final, official merit list and ranks will be generated by the Centre for Electronic Governance during the actual REAP-2026 Centralized Admission Process after thorough verification of original documents.")

# --- 2. INPUT LAYOUT ---
with st.form("candidate_form", clear_on_submit=False):
    st.markdown("### 📋 Candidate Evaluation Details")

    with st.expander("🎓 Step 1: Academic Information", expanded=True):
        c1, c2 = st.columns(2)
        with c1:
            name = st.text_input("Candidate Name", "")
            perc_12th = st.number_input("12th Board (%)", min_value=0.0, max_value=100.0, value=75.0, step=0.1,
                                        help="Percentage obtained in class 12th. Eligibility cutoff is 45% for GEN and 40% for Reserved categories.")
            jee_score = st.number_input("JEE Percentile (0 if none)", min_value=0.0, max_value=100.0, value=25.0,
                                        step=0.1,
                                        help="Rank obtained in JEE (Mains) 2026. Evaluated as Priority 2. Requires a minimum of 20 percentile.")
        with c2:
            dob = st.date_input("Date of Birth", datetime(2005, 1, 1),
                                help="Used as the final tie-breaker. Older candidates rank higher.")
            perc_dip = st.number_input("D.Voc / Diploma (%)", min_value=0.0, max_value=100.0, value=0.0, step=0.1,
                                       help="Percentage obtained in D.Voc (NCrF level 4) or approved Diploma. Evaluated as Priority 4.")
            perc_10th = st.number_input("10th Board (%)", min_value=0.0, max_value=100.0, value=80.0, step=0.1,
                                        help="Used internally as a secondary tie-breaker if Effective Score and 12th Board % are identical.")

    with st.expander("🌍 Step 2: Demographics & Base Category", expanded=True):
        c3, c4 = st.columns(2)
        with c3:
            gender = st.selectbox("Gender", ["M", "F", "Other"],
                                  help="Female candidates receive a 30% horizontal reservation across all categories (Rajasthan Domicile Only).")
            category = st.selectbox("Base Category", ["GEN", "OBC (Non-Creamy)", "SC", "ST", "MBC (Non-Creamy)", "EWS"],
                                    help="Determines your vertical reservation quota in the State Matrix.")
        with c4:
            area = st.selectbox("Area Type", ["Non-TSP", "TSP"],
                                help="Tribal Sub Plan (TSP) area. 45% of the ST quota is horizontally reserved for TSP candidates. Only applicable if Category is ST.")
            domicile = st.selectbox("Domicile", ["Rajasthan", "Outside Rajasthan"],
                                    help="Non-Rajasthan candidates are strictly processed as UR/GEN with NO horizontal reservations and are only eligible for Self Financed Seats (SFS).")

    with st.expander("⭐ Step 3: Supernumerary and Other Quotas", expanded=False):
        c5, c6 = st.columns(2)
        with c5:
            pwd_quota = st.checkbox("Person with Special Ability (PwD)",
                                    help="Grants a 5% horizontal reservation (Rajasthan Domicile Only).")
            income_less_8l = st.checkbox("Income < ₹8.00 Lakhs (TFWS)",
                                         help="Determines eligibility for the Tuition Fee Waiver Scheme (TFWS), which comprises up to 5% supernumerary seats.")
            km_quota = st.checkbox("Kashmiri Migrant (KM)",
                                   help="5% additional supernumerary seats for Kashmiri Pandits/Hindu Families. Processed internally as Outside Rajasthan + GEN.")
            wp_quota = st.checkbox("Working Professional (WP)",
                                   help="Exclusive supernumerary seats for candidates with 2+ years experience and workplace within 80km. Removes candidate from the main admission pool.")
            fn_quota = st.checkbox("Foreign National / OCI / Gulf",
                                   help="15% supernumerary seats over approved intake for Foreign Nationals and Children of Indian workers in Gulf countries. Removed from main admission pool.")
        with c6:
            exs_priority = st.selectbox("Ex-Servicemen (EXS)", [
                "None", "EXS1 (Killed in action)", "EXS2 (Disabled in action)", "EXS3 (Died in service)",
                "EXS4 (Disabled in service)", "EXS5 (Gallantry Awards)", "EXS6 (Wards of EXS)",
                "EXS7 (Wives of EXS)", "EXS8 (Wards of Serving)", "EXS9 (Wives of Serving)"
            ], help="3% horizontal reservation for dependents of Defence personnel (Rajasthan Domicile Only).")

            sports_quota = st.checkbox("Valid Sports Quota", help="Only available for Rajasthan Domicile candidates.")
            sports_cat = st.selectbox("Sports Category", ["None", "A (Absolute Priority)", "B", "C", "D", "E"],
                                      help="System automatically applies weightage: A/B (+7), C (+5), D (+4), E (+2). Category A has max 5% seat capacity before falling back to B.")

    st.markdown("<br>", unsafe_allow_html=True)
    submit_btn_col1, submit_btn_col2, submit_btn_col3 = st.columns([1, 1, 1])
    with submit_btn_col2:
        submitted = st.form_submit_button("🚀 Run Eligibility Simulator", type="secondary", use_container_width=True)

# --- 3. ALGORITHM EXECUTION & DASHBOARD ---
if submitted:
    st.toast("Merit calculation complete!", icon="✅")
    st.divider()

    backend_category = category.split(" ")[0]

    # --- DOMICILE & RESERVATION OVERRIDE LOGIC ---
    km_override_applied = False
    dom_override_applied = False
    res_override_applied = False

    if km_quota:
        domicile = "Outside Rajasthan"
        backend_category = "GEN"
        km_override_applied = True

    if domicile != "Rajasthan":
        if backend_category != "GEN":
            backend_category = "GEN"
            dom_override_applied = True

        # Nullify all horizontal reservations for Out of State candidates
        if pwd_quota or exs_priority != "None" or area == "TSP" or sports_quota:
            res_override_applied = True

        pwd_quota = False
        exs_priority = "None"
        area = "Non-TSP"
        sports_quota = False

    req_cutoff = 45.0 if backend_category == "GEN" else 40.0
    eligible_12th = perc_12th >= req_cutoff
    eligible_dip = perc_dip >= req_cutoff
    is_eligible = eligible_12th or eligible_dip

    st.markdown("## 📊 Candidate Eligibility Dashboard")

    if not is_eligible:
        cat_text = "Kashmiri Migrant" if km_override_applied else backend_category

        if perc_12th > 0 and perc_dip == 0:
            st.error(
                f"### ❌ Disqualified: Failed Eligibility Criteria\n{cat_text} Candidate requires {req_cutoff}% in 12th. Candidate scored in 12th: {perc_12th}%.")
        elif perc_dip > 0 and perc_12th == 0:
            st.error(
                f"### ❌ Disqualified: Failed Eligibility Criteria\n{cat_text} Candidate requires {req_cutoff}% in Diploma. Candidate scored in Diploma: {perc_dip}%.")
        else:
            st.error(
                f"### ❌ Disqualified: Failed Eligibility Criteria\n{cat_text} Candidate requires {req_cutoff}% in 12th OR Diploma. Candidate scored in 12th: {perc_12th}%, Diploma: {perc_dip}%.")

    else:
        jee_basis = jee_score >= 20.0
        srsec_basis = not jee_basis and eligible_12th

        if jee_basis:
            academic_priority = "Priority 2 (JEE)"
            base_score = jee_score
        elif srsec_basis:
            academic_priority = "Priority 3 (12th)"
            base_score = perc_12th
        else:
            academic_priority = "Priority 4 (Diploma)"
            base_score = perc_dip

        # Automated Sports Weightage & Priority A Logic
        effective_score = base_score
        sports_bonus_applied = False
        sports_weight = 0.0
        is_category_a = False
        cat_letter = "None"

        if domicile == "Rajasthan" and sports_quota and sports_cat != "None" and not wp_quota and not fn_quota:
            cat_letter = sports_cat.split(" ")[0]
            if cat_letter == "A":
                is_category_a = True
                sports_weight = 7.0
            elif cat_letter == "B":
                sports_weight = 7.0
            elif cat_letter == "C":
                sports_weight = 5.0
            elif cat_letter == "D":
                sports_weight = 4.0
            elif cat_letter == "E":
                sports_weight = 2.0

            effective_score += sports_weight
            sports_bonus_applied = True

        display_priority = "Priority 1 (Sports A)" if is_category_a else academic_priority

        # --- DASHBOARD LAYOUT WITH SPEEDOMETER ---
        dash_col1, dash_col2 = st.columns([1.5, 1])

        with dash_col1:
            mc1, mc2 = st.columns(2)
            mc1.metric(label="Calculated Priority Tier", value=display_priority,
                       delta="Highest Eligible" if jee_basis else None)

            # Suppress delta warning for WP and FN exclusive pools to avoid confusion
            mc2.metric(label="Final Matrix Category", value=backend_category,
                       delta="Out-of-State Override" if (
                                   dom_override_applied and not wp_quota and not fn_quota) else None, delta_color="off")

            if is_category_a:
                st.info(
                    f"**Note:** Priority 1 is capped at 5% of total course seats. If candidate does not secure a Priority 1 seat, he/she will fall back to **{academic_priority}** with an Effective Score of {effective_score:.2f} (Adding +7.0).")

            if km_override_applied:
                st.warning(
                    "⚠️ **Kashmiri Migrant Rule Applied:** For main state matrix processing, Domicile is forced to 'Outside Rajasthan' and Category forced to 'GEN'.")
            elif domicile != "Rajasthan" and not wp_quota and not fn_quota:
                # Warning suppressed for WP and FN candidates
                st.warning(
                    "⚠️ **Out-of-State Rule Applied:** Candidate is not a domicile of Rajasthan. Vertical/horizontal reservations are nullified, and the candidate is **excluded from the main State Merit (`mmerit`)**. The candidate is eligible **ONLY for Self Financed Seats (SFS)** under the Outside Rajasthan Quota.")

            st.markdown("### 🏆 Projected Ranking Lists")

            # EXCLUSIVE POOL OVERRIDES
            if wp_quota:
                st.error(
                    "🛑 **WORKING PROFESSIONAL EXCLUSIVE POOL**\n\nAs per AICTE norms, the candidate is removed from the main admission pool and placed exclusively in the Working Professionals list (`mwp`). No other state or horizontal reservations apply.")
                ranks = ["🔹 `mwp` (Working Professional Supernumerary Quota)"]
                st.success("Based on master tie-breaker logic, candidate will be positioned in the following sequence:")
                st.info("\n".join(ranks))

            elif fn_quota:
                st.error(
                    "🛑 **FOREIGN NATIONAL / GULF EXCLUSIVE POOL**\n\nAs per AICTE norms, the candidate is placed exclusively in the Foreign National list (`mfn`). No state vertical or horizontal reservations apply.")
                ranks = ["🔹 `mfn` (Foreign National/OCI/Gulf Quota - 15% Supernumerary)"]
                st.success("Based on master tie-breaker logic, candidate will be positioned in the following sequence:")
                st.info("\n".join(ranks))

            else:
                # MAIN STATE MATRIX (If not WP or FN)
                ranks = []

                # Apply mmerit and Horizontal Reservations ONLY if Domicile is Rajasthan
                if domicile == "Rajasthan":
                    ranks.append("🔹 `mmerit` (Overall State Merit)")
                    if gender == "F": ranks.append("🔹 `mgenf` (Overall General Female - 30% Horizontal)")

                    if backend_category in ["OBC", "SC", "ST", "MBC", "EWS"]:
                        ranks.append(f"🔹 `m{backend_category.lower()}` (Category {backend_category})")
                        if gender == "F": ranks.append(
                            f"🔹 `m{backend_category.lower()}f` (Category {backend_category} Female)")

                    if backend_category == "ST" and area == "TSP":
                        ranks.append("🔹 `mtsp` (TSP Quota - 45% of ST Reserved)")
                        if gender == "F": ranks.append("🔹 `mtspf` (TSP Female Quota)")

                    if pwd_quota:
                        ranks.append("🔹 `mpwd` (Persons with Special Ability - 5% Horizontal)")
                        if gender == "F": ranks.append("🔹 `mpwdf` (PwD Female)")

                    if exs_priority != "None":
                        tier_num = exs_priority.split(" ")[0]
                        ranks.append(f"🔹 `mexs` (Ex-Servicemen Priority Sort - Tier {tier_num})")
                        if gender == "F": ranks.append("🔹 `mexsf` (Ex-Servicemen Female)")

                    if sports_quota and sports_cat != "None":
                        if cat_letter == "A":
                            ranks.append(
                                f"🔹 `msqa` (Priority 1: Sports Category A - Max 5% capacity, then falls back to Sports Category B)")
                        else:
                            ranks.append(f"🔹 `msqa` (Sports Priority Sort - Category {cat_letter})")
                else:
                    # Outside Rajasthan gets pure MOR list exclusively
                    ranks.append(
                        "🔹 `mor` (Outside Rajasthan Quota - 15%) - **Eligible for Self Financed Seats (SFS) ONLY**")

                # Supernumerary quotas apply independently of native matrices
                if km_quota:
                    ranks.append("🔹 `mkm` (Kashmiri Migrant Supernumerary Quota - 5%)")
                    if gender == "F": ranks.append("🔹 `mkmf` (Kashmiri Migrant Female)")
                if income_less_8l: ranks.append("🔹 `mtfw` (Tuition Fee Waiver Scheme Supernumerary - 5%)")

                st.success(
                    "Based on master tie-breaker logic, candidate will be positioned in the following sequences:")
                st.info("\n".join(ranks))

        with dash_col2:
            fig = go.Figure(go.Indicator(
                mode="gauge+number+delta",
                value=effective_score,
                domain={'x': [0, 1], 'y': [0, 1]},
                title={'text': "Effective Academic Score", 'font': {'size': 22}},
                delta={'reference': base_score, 'increasing': {'color': "#10B981"}, 'position': "top"},
                gauge={
                    'axis': {'range': [None, 120], 'tickwidth': 1},
                    'bar': {'color': "#D4AF37", 'thickness': 0.75},
                    'bgcolor': "rgba(0,0,0,0)",
                    'borderwidth': 2,
                    'bordercolor': "gray",
                    'steps': [
                        {'range': [0, req_cutoff], 'color': "rgba(239, 68, 68, 0.4)"},
                        {'range': [req_cutoff, 75], 'color': "rgba(245, 158, 11, 0.3)"},
                        {'range': [75, 120], 'color': "rgba(16, 185, 129, 0.3)"}],
                    'threshold': {
                        'line': {'color': "gray", 'width': 4},
                        'thickness': 0.75,
                        'value': effective_score}
                }
            ))

            fig.update_layout(
                paper_bgcolor="rgba(0,0,0,0)",
                height=350,
                margin=dict(l=20, r=20, t=50, b=20)
            )

            st.plotly_chart(fig, use_container_width=True, theme="streamlit")

            if sports_bonus_applied:
                st.caption(f"✨ Score includes **+{sports_weight} points** for Sports Quota Category {cat_letter}.")
            else:
                st.caption("Score based purely on academic priority tier.")
