import streamlit as st
import pandas as pd
import time
from datetime import datetime
import os
import base64
import plotly.graph_objects as go

# --- SAFE FPDF IMPORT FOR REPORT GENERATION ---
try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False

# --- 1. UI CONFIGURATION & THEME ---
st.set_page_config(page_title="REAP-2026 Eligibility Simulator", page_icon="🏛️", layout="wide")

# Columns for Language Selection at the top right
col_hdr, col_lang = st.columns([5, 1.2])
with col_lang:
    selected_language = st.selectbox(
        "🌐 Language / भाषा चुनें",
        ["English", "हिन्दी (Hindi)"],
        index=0,
        help="Switch interface language / इंटरफ़ेस भाषा बदलें"
    )

is_hindi = (selected_language == "हिन्दी (Hindi)")

# --- 2. TRANSLATION DICTIONARY (BILINGUAL ENGINE) ---
T = {
    "app_title": "REAP 2026" if not is_hindi else "रीप 2026",
    "app_subtitle": "CENTRALIZED ADMISSION PROCESS • ELIGIBILITY SIMULATOR" if not is_hindi else "केन्द्रीकृत प्रवेश प्रक्रिया • पात्रता सिम्युलेटर",
    "disclaimer_title": "OFFICIAL DISCLAIMER:" if not is_hindi else "आधिकारिक अस्वीकरण (Disclaimer):",
    "disclaimer_text": (
        "This Eligibility Simulator is provided for informational and guidance purposes only. The projected priority tiers, "
        "effective scores, and ranking lists generated by this tool are tentative and based entirely on the unverified data "
        "entered by the user. The final, official merit list and ranks will be generated by the Centre for Electronic Governance "
        "during the actual REAP-2026 Centralized Admission Process after thorough verification of original documents."
    ) if not is_hindi else (
        "यह पात्रता सिम्युलेटर केवल सूचनात्मक और मार्गदर्शन उद्देश्यों के लिए प्रदान किया गया है। इस टूल द्वारा उत्पन्न अनुमानित प्राथमिकता "
        "स्तर (priority tiers), प्रभावी अंक (effective scores) और रैंकिंग सूचियां पूरी तरह से अनंतिम (tentative) हैं और उपयोगकर्ता द्वारा "
        "दर्ज किए गए असत्यापित डेटा पर आधारित हैं। अंतिम, आधिकारिक योग्यता सूची और रैंक वास्तविक REAP-2026 केन्द्रीकृत प्रवेश प्रक्रिया "
        "के दौरान मूल दस्तावेजों के गहन सत्यापन के बाद सेंटर फॉर इलेक्ट्रॉनिक गवर्नेंस (CEG) द्वारा ही जारी की जाएगी।"
    ),
    "eval_details_header": "📋 Candidate Evaluation Details" if not is_hindi else "📋 अभ्यर्थी मूल्यांकन विवरण",
    "step1_title": "🎓 Step 1: Academic Information" if not is_hindi else "🎓 चरण 1: शैक्षणिक जानकारी",
    "cand_name": "Candidate Name" if not is_hindi else "अभ्यर्थी का नाम",
    "dob": "Date of Birth" if not is_hindi else "जन्म तिथि",
    "dob_help": "Used as the final tie-breaker. Older candidates rank higher." if not is_hindi else "अंतिम टाई-ब्रेकर के रूप में उपयोग किया जाता है। अधिक आयु वाले अभ्यर्थी को उच्च रैंक मिलती है।",
    "perc_10th": "10th Board (%)" if not is_hindi else "10वीं बोर्ड (%)",
    "perc_10th_help": (
        "Used internally as a secondary tie-breaker if Effective Score and Qualifying % are identical."
    ) if not is_hindi else (
        "प्रभावी अंक और पात्रता % समान होने की स्थिति में द्वितीयक टाई-ब्रेकर के रूप में आंतरिक रूप से उपयोग किया जाता है।"
    ),
    "qual_basis": "Select Qualifying Basis" if not is_hindi else "पात्रता परीक्षा का आधार चुनें",
    "jee_score": "JEE Mains Percentile (0 if none)" if not is_hindi else "जेईई मेन्स पर्सेंटाइल (यदि कोई नहीं है तो 0 दर्ज करें)",
    "jee_help": (
        "Rank obtained in JEE (Mains) 2026. Evaluated as Priority 2. Requires a minimum of 20 percentile (Not applicable for Diploma/D.Voc)."
    ) if not is_hindi else (
        "जेईई (मेन्स) 2026 में प्राप्त रैंक। प्राथमिकता 2 के तहत मूल्यांकन। न्यूनतम 20 पर्सेंटाइल आवश्यक (डिप्लोमा/D.Voc के लिए लागू नहीं)।"
    ),
    "diploma_success": (
        "✅ **Note:** As a Diploma holder, you are considered equivalent to PCM. You are eligible for **Group-1 (All Branches)** and evaluated under **Priority 3**."
    ) if not is_hindi else (
        "✅ **नोट:** डिप्लोमा धारक के रूप में, आपको PCM के समकक्ष माना जाता है। आप **ग्रुप-1 (सभी शाखाओं)** के लिए पात्र हैं और **प्राथमिकता 3** के तहत मूल्यांकन किया जाएगा।"
    ),
    "diploma_pct": "Diploma (%)" if not is_hindi else "डिप्लोमा (%)",
    "dvoc_info": (
        "📌 **Note:** You are eligible for the relevant branch in which you have passed the D.Voc. Evaluated under **Priority 4**."
    ) if not is_hindi else (
        "📌 **नोट:** आप उस प्रासंगिक शाखा के लिए पात्र हैं जिसमें आपने D.Voc उत्तीर्ण किया है। **प्राथमिकता 4** के तहत मूल्यांकन किया जाएगा।"
    ),
    "dvoc_pct": "D.Voc (%)" if not is_hindi else "D.Voc (%)",
    "cutoff_help": "Eligibility cutoff is 45% for GEN and 40% for Reserved categories." if not is_hindi else "पात्रता कटऑफ सामान्य (GEN) के लिए 45% और आरक्षित श्रेणियों के लिए 40% है।",
    "subject_12_title": "Select 12th Board Subjects" if not is_hindi else "12वीं बोर्ड विषयों का चयन करें",
    "subject_12_caption": (
        "📌 **Note:** Choose 3 distinct mandatory subjects. If your stream is strictly Agriculture, select **'Agriculture Stream'** as Subject 1 (Subjects 2 and 3 will be locked automatically)."
    ) if not is_hindi else (
        "📌 **नोट:** 3 अलग-अलग अनिवार्य विषयों का चयन करें। यदि आपकी स्ट्रीम केवल कृषि (Agriculture) है, तो विषय 1 के रूप में **'Agriculture Stream'** चुनें (विषय 2 और विषय 3 स्वतः ही लॉक हो जाएंगे)।"
    ),
    "sub1_label": "Subject 1" if not is_hindi else "विषय 1",
    "sub2_label": "Subject 2" if not is_hindi else "विषय 2",
    "sub3_label": "Subject 3" if not is_hindi else "विषय 3",
    "perc_12th_label": "12th Board (%)" if not is_hindi else "12वीं बोर्ड (%)",
    "step2_title": "🌍 Step 2: Demographics & Base Category" if not is_hindi else "🌍 चरण 2: जनसांख्यिकी और मूल श्रेणी",
    "gender": "Gender" if not is_hindi else "लिंग",
    "gender_help": "Female candidates receive a 30% horizontal reservation across all categories (Rajasthan Domicile Only)." if not is_hindi else "महिला अभ्यर्थियों को सभी श्रेणियों में 30% क्षैतिज आरक्षण प्राप्त होता है (केवल राजस्थान मूल निवासी)।",
    "base_cat": "Base Category" if not is_hindi else "मूल श्रेणी",
    "base_cat_help": "Determines your vertical reservation quota in the State Matrix." if not is_hindi else "स्टेट मैट्रिक्स में आपके ऊर्ध्वाधर (vertical) आरक्षण कोटा को निर्धारित करता है।",
    "area": "Area Type" if not is_hindi else "क्षेत्र का प्रकार",
    "area_help": "Tribal Sub Plan (TSP) area. 45% of the ST quota is horizontally reserved for TSP candidates. Only applicable if Category is ST." if not is_hindi else "जनजातीय उप-योजना (TSP) क्षेत्र। ST कोटा का 45% TSP उम्मीदवारों के लिए क्षैतिज रूप से आरक्षित है। केवल तभी लागू जब श्रेणी ST हो।",
    "domicile": "Domicile" if not is_hindi else "मूल निवास (Domicile)",
    "domicile_help": "Non-Rajasthan candidates are strictly processed as UR/GEN with NO horizontal reservations and are only eligible for Self Financed Seats (SFS)." if not is_hindi else "गैर-राजस्थान अभ्यर्थियों को बिना किसी क्षैतिज आरक्षण के कड़ाई से UR/GEN के रूप में माना जाता है और वे केवल स्व-वित्तपोषित सीटों (SFS) के लिए पात्र हैं।",
    "step3_title": "⭐ Step 3: Supernumerary and Other Quotas" if not is_hindi else "⭐ चरण 3: अधिसंख्य (Supernumerary) और अन्य कोटा",
    "pwd_label": "Person with Special Ability (PwD)" if not is_hindi else "विशेष योग्यजन (PwD)",
    "pwd_help": "Grants a 5% horizontal reservation (Rajasthan Domicile Only)." if not is_hindi else "5% क्षैतिज आरक्षण प्रदान करता है (केवल राजस्थान मूल निवासी)।",
    "tfws_label": "Income < ₹8.00 Lakhs (TFWS)" if not is_hindi else "आय < ₹8.00 लाख (TFWS)",
    "tfws_help": "Determines eligibility for the Tuition Fee Waiver Scheme (TFWS), which comprises up to 5% supernumerary seats." if not is_hindi else "ट्यूशन फीस माफी योजना (TFWS) के लिए पात्रता निर्धारित करता है, जिसमें 5% तक अधिसंख्य सीटें शामिल हैं।",
    "km_label": "Kashmiri Migrant (KM)" if not is_hindi else "कश्मीरी प्रवासी (KM)",
    "km_help": "5% additional supernumerary seats for Kashmiri Pandits/Hindu Families. Processed internally as Outside Rajasthan + GEN." if not is_hindi else "कश्मीरी पंडितों/हिंदू परिवारों के लिए 5% अतिरिक्त अधिसंख्य सीटें। आंतरिक रूप से गैर-राजस्थान + GEN के रूप में संसाधित किया जाता है।",
    "wp_label": "Working Professional (WP)" if not is_hindi else "कार्यरत पेशेवर (WP)",
    "wp_help": "Exclusive supernumerary seats for candidates with 2+ years experience and workplace within 80km. Removes candidate from the main admission pool." if not is_hindi else "2+ वर्ष के अनुभव और 80 किमी के भीतर कार्यस्थल वाले उम्मीदवारों के लिए विशेष अधिसंख्य सीटें। अभ्यर्थी को मुख्य प्रवेश पूल से अलग करता है।",
    "fn_label": "Foreign National / OCI / Gulf" if not is_hindi else "विदेशी नागरिक / OCI / खाड़ी देश कोटा",
    "fn_help": "15% supernumerary seats over approved intake for Foreign Nationals and Children of Indian workers in Gulf countries. Removed from main admission pool." if not is_hindi else "विदेशी नागरिकों और खाड़ी देशों में कार्यरत भारतीय श्रमिकों के बच्चों के लिए स्वीकृत सीटों से 15% अतिरिक्त अधिसंख्य सीटें। मुख्य प्रवेश पूल से अलग किया जाता है।",
    "exs_label": "Ex-Servicemen (EXS)" if not is_hindi else "भूतपूर्व सैनिक (EXS)",
    "exs_help": "3% horizontal reservation for dependents of Defence personnel (Rajasthan Domicile Only)." if not is_hindi else "रक्षा कर्मियों के आश्रितों के लिए 3% क्षैतिज आरक्षण (केवल राजस्थान मूल निवासी)।",
    "sports_label": "Valid Sports Quota" if not is_hindi else "वैध खेल कोटा (Sports Quota)",
    "sports_cat_label": "Sports Category" if not is_hindi else "खेल श्रेणी (Sports Category)",
    "sports_cat_help": "System automatically applies weightage: A/B (+7), C (+5), D (+4), E (+2). Category A has max 5% seat capacity before falling back to B." if not is_hindi else "सिस्टम स्वचालित रूप से वेटेज लागू करता है: A/B (+7), C (+5), D (+4), E (+2)। श्रेणी B में गिरने से पहले श्रेणी A की अधिकतम 5% सीट क्षमता होती है।",
    "submit_btn": "🚀 Run Eligibility Simulator" if not is_hindi else "🚀 पात्रता सिम्युलेटर चलाएं",
    "toast_done": "Eligibility Calculation Completed!" if not is_hindi else "पात्रता गणना पूरी हुई!",
    "err_qual_exam": "⚠️ **Action Required:** Please select a Qualifying Basis in Step 1 to proceed." if not is_hindi else "⚠️ **आवश्यक कार्रवाई:** आगे बढ़ने के लिए कृपया चरण 1 में पात्रता परीक्षा का आधार चुनें।",
    "dashboard_title": "📊 Candidate Eligibility Dashboard" if not is_hindi else "📊 अभ्यर्थी पात्रता डैशबोर्ड",
    "err_3_subjects": "❌ **Action Required:** Please select exactly three subjects from the dropdowns." if not is_hindi else "❌ **आवश्यक कार्रवाई:** कृपया ड्रॉपडाउन से ठीक तीन विषयों का चयन करें।",
    "group_eligible_msg": "Based on your subjects, you are eligible for:" if not is_hindi else "आपके विषयों के आधार पर, आप इनके लिए पात्र हैं:",
    "disq_aicte": "❌ Disqualified: This subject combination does not meet AICTE eligibility criteria." if not is_hindi else "❌ अपात्र: यह विषय संयोजन एआईसीटीई (AICTE) पात्रता मानदंडों को पूरा नहीं करता है।",
    "disq_cutoff": "### ❌ Disqualified: Failed Eligibility Criteria" if not is_hindi else "### ❌ अपात्र: पात्रता मानदंड विफल",
    "require_marks": "Candidate requires" if not is_hindi else "अभ्यर्थी को आवश्यकता है",
    "scored_marks": "Candidate scored" if not is_hindi else "अभ्यर्थी ने प्राप्त किए",
    "priority_metric": "Calculated Priority Tier" if not is_hindi else "परिकलित प्राथमिकता स्तर",
    "matrix_metric": "Final Matrix Category" if not is_hindi else "अंतिम मैट्रिक्स श्रेणी",
    "sports_fallback_msg": (
        "**Note:** Priority 1 is capped at 5% of total course seats. If candidate does not secure a Priority 1 seat, "
        "he/she will fall back to **{academic_priority}** with an Effective Academic Score of {effective_score:.2f}."
    ) if not is_hindi else (
        "**नोट:** प्राथमिकता 1 कुल कोर्स सीटों के 5% तक ही सीमित है। यदि अभ्यर्थी प्राथमिकता 1 सीट प्राप्त नहीं कर पाता है, "
        "तो वह **{academic_priority}** पर वापस आ जाएगा, जिसमें प्रभावी शैक्षणिक स्कोर {effective_score:.2f} होगा।"
    ),
    "km_rule_warning": (
        "⚠️ **Kashmiri Migrant Rule Applied:** For main state matrix processing, Domicile is forced to "
        "'Outside Rajasthan' and Category forced to 'GEN'."
    ) if not is_hindi else (
        "⚠️ **कश्मीरी प्रवासी नियम लागू:** मुख्य राज्य मैट्रिक्स प्रसंस्करण के लिए, मूल निवास को 'Outside Rajasthan' "
        "और श्रेणी को 'GEN' के रूप में बाध्य किया गया है।"
    ),
    "out_of_state_warning": (
        "⚠️ **Out-of-State Rule Applied:** Candidate is not a domicile of Rajasthan. Vertical/horizontal reservations are nullified, "
        "and the candidate is **excluded from the main State Merit (`mmerit`)**. Eligible **ONLY for Self Financed Seats (SFS)**."
    ) if not is_hindi else (
        "⚠️ **आउट-ऑफ-स्टेट नियम लागू:** अभ्यर्थी राजस्थान का मूल निवासी नहीं है। ऊर्ध्वाधर/क्षैतिज आरक्षण निरस्त कर दिए गए हैं, "
        "और अभ्यर्थी को **मुख्य राज्य योग्यता सूची (`mmerit`) से बाहर** कर दिया गया है। केवल **स्व-वित्तपोषित सीटों (SFS)** के लिए पात्र।"
    ),
    "projected_lists_title": "🏆 Projected Ranking Lists" if not is_hindi else "🏆 अनुमानित रैंकिंग सूचियां (Projected Ranking Lists)",
    "wp_exclusive_error": (
        "🛑 **WORKING PROFESSIONAL EXCLUSIVE POOL**\n\nCandidate is removed from the main admission pool and placed "
        "exclusively in the Working Professionals list (`mwp`). No other state or horizontal reservations apply."
    ) if not is_hindi else (
        "🛑 **कार्यरत पेशेवर (WORKING PROFESSIONAL) विशेष पूल**\n\nअभ्यर्थी को मुख्य प्रवेश पूल से हटा दिया जाता है और विशेष रूप से "
        "कार्यरत पेशेवर सूची (`mwp`) में रखा जाता है। कोई अन्य राज्य या क्षैतिज आरक्षण लागू नहीं होता है।"
    ),
    "fn_exclusive_error": (
        "🛑 **FOREIGN NATIONAL / GULF EXCLUSIVE POOL**\n\nCandidate is placed exclusively in the Foreign National list (`mfn`). "
        "No state vertical or horizontal reservations apply."
    ) if not is_hindi else (
        "🛑 **विदेशी नागरिक / खाड़ी देश विशेष पूल**\n\nअभ्यर्थी को विशेष रूप से विदेशी नागरिक सूची (`mfn`) में रखा जाता है। "
        "कोई राज्य ऊर्ध्वाधर या क्षैतिज आरक्षण लागू नहीं होता है।"
    ),
    "tiebreaker_seq_msg": (
        "Based on master tie-breaker logic, candidate will be positioned in the following sequences:"
    ) if not is_hindi else (
        "मास्टर टाई-ब्रेकर लॉजिक के आधार पर, उम्मीदवार को निम्नलिखित अनुक्रमों (पूल) में स्थान दिया जाएगा:"
    ),
    "eff_academic_score": "Effective Academic Score" if not is_hindi else "प्रभावी शैक्षणिक अंक",
    "sports_bonus_caption": "✨ Score includes **+{sports_weight} points** for Sports Quota Category {cat_letter}." if not is_hindi else "✨ स्कोर में स्पोर्ट्स कोटा श्रेणी {cat_letter} के लिए **+{sports_weight} अंक** शामिल हैं।",
    "pure_academic_caption": "Score based purely on academic priority tier." if not is_hindi else "विशुद्ध रूप से शैक्षणिक प्राथमिकता स्तर पर आधारित स्कोर।",
    "download_report_btn": "📥 Download Official Eligibility Report (PDF)" if not is_hindi else "📥 आधिकारिक पात्रता रिपोर्ट डाउनलोड करें (PDF)",
    "pdf_install_helper": "💡 To enable PDF downloads, please install the library on your hosting server by running: `pip install fpdf2`" if not is_hindi else "💡 PDF डाउनलोड सक्षम करने के लिए, कृपया होस्टिंग सर्वर पर यह कमांड चलाकर लाइब्रेरी इंस्टॉल करें: `pip install fpdf2`",
}

# --- 3. DROP DOWN OPTIONS & BILINGUAL MAPS ---
qual_exam_options = ["-- Select --", "12th Board", "Diploma", "D.Voc"] if not is_hindi else ["-- चुनें --", "12वीं बोर्ड", "डिप्लोमा", "डी.वोक"]
qual_exam_map = {
    "-- Select --": "-- Select --", "-- चुनें --": "-- Select --",
    "12th Board": "12th Board", "12वीं बोर्ड": "12th Board",
    "Diploma": "Diploma", "डिप्लोमा": "Diploma",
    "D.Voc": "D.Voc", "डी.वोक": "D.Voc"
}

gender_options = ["M", "F", "Other"] if not is_hindi else ["M (पुरुष)", "F (महिला)", "Other (अन्य)"]
gender_map = {
    "M": "M", "M (पुरुष)": "M",
    "F": "F", "F (महिला)": "F",
    "Other": "Other", "Other (अन्य)": "Other"
}

category_options = ["GEN", "OBC (Non-Creamy)", "SC", "ST", "MBC (Non-Creamy)", "EWS"] if not is_hindi else ["GEN (सामान्य)", "OBC (नॉन-क्रीमी लेयर)", "SC (अनुसूचित जाति)", "ST (अनुसूचित जनजाति)", "MBC (नॉन-क्रीमी लेयर)", "EWS (कमजोर वर्ग)"]
category_map = {
    "GEN": "GEN", "GEN (सामान्य)": "GEN",
    "OBC (Non-Creamy)": "OBC (Non-Creamy)", "OBC (नॉन-क्रीमी लेयर)": "OBC (Non-Creamy)",
    "SC": "SC", "SC (अनुसूचित जाति)": "SC",
    "ST": "ST", "ST (अनुसूचित जनजाति)": "ST",
    "MBC (Non-Creamy)": "MBC (Non-Creamy)", "MBC (नॉन-क्रीमी लेयर)": "MBC (Non-Creamy)",
    "EWS": "EWS", "EWS (कमजोर वर्ग)": "EWS"
}

area_options = ["Non-TSP", "TSP"] if not is_hindi else ["गैर-टीएसपी (Non-TSP)", "टीएसपी (TSP)"]
area_map = {
    "Non-TSP": "Non-TSP", "गैर-टीएसपी (Non-TSP)": "Non-TSP",
    "TSP": "TSP", "टीएसपी (TSP)": "TSP"
}

domicile_options = ["Rajasthan", "Outside Rajasthan"] if not is_hindi else ["राजस्थान (Rajasthan)", "राजस्थान से बाहर (Outside Rajasthan)"]
domicile_map = {
    "Rajasthan": "Rajasthan", "राजस्थान (Rajasthan)": "Rajasthan",
    "Outside Rajasthan": "Outside Rajasthan", "राजस्थान से बाहर (Outside Rajasthan)": "Outside Rajasthan"
}

exs_options = [
    "None", "EXS1 (Killed in action)", "EXS2 (Disabled in action)", "EXS3 (Died in service)",
    "EXS4 (Disabled in service)", "EXS5 (Gallantry Awards)", "EXS6 (Wards of EXS)",
    "EXS7 (Wives of EXS)", "EXS8 (Wards of Serving)", "EXS9 (Wives of Serving)"
] if not is_hindi else [
    "कोई नहीं", "EXS1 (युद्ध में शहीद)", "EXS2 (युद्ध में विकलांग)", "EXS3 (सेवा के दौरान मृत्यु)",
    "EXS4 (सेवा के दौरान विकलांग)", "EXS5 (वीरता पुरस्कार)", "EXS6 (भूतपूर्व सैनिकों के आश्रित)",
    "EXS7 (भूतपूर्व सैनिकों की पत्नियां)", "EXS8 (सेवारत कर्मियों के आश्रित)", "EXS9 (सेवारत कर्मियों की पत्नियां)"
]
exs_map = {
    "None": "None", "कोई नहीं": "None",
    "EXS1 (Killed in action)": "EXS1 (Killed in action)", "EXS1 (युद्ध में शहीद)": "EXS1 (Killed in action)",
    "EXS2 (Disabled in action)": "EXS2 (Disabled in action)", "EXS2 (युद्ध में विकलांग)": "EXS2 (Disabled in action)",
    "EXS3 (Died in service)": "EXS3 (Died in service)", "EXS3 (सेवा के दौरान मृत्यु)": "EXS3 (Died in service)",
    "EXS4 (Disabled in service)": "EXS4 (Disabled in service)", "EXS4 (सेवा के दौरान विकलांग)": "EXS4 (Disabled in service)",
    "EXS5 (Gallantry Awards)": "EXS5 (Gallantry Awards)", "EXS5 (वीरता पुरस्कार)": "EXS5 (Gallantry Awards)",
    "EXS6 (Wards of EXS)": "EXS6 (Wards of EXS)", "EXS6 (भूतपूर्व सैनिकों के आश्रित)": "EXS6 (Wards of EXS)",
    "EXS7 (Wives of EXS)": "EXS7 (Wives of EXS)", "EXS7 (भूतपूर्व सैनिकों की पत्नियां)": "EXS7 (Wives of EXS)",
    "EXS8 (Wards of Serving)": "EXS8 (Wards of Serving)", "EXS8 (सेवारत कर्मियों के आश्रित)": "EXS8 (Wards of Serving)",
    "EXS9 (Wives of Serving)": "EXS9 (Wives of Serving)", "EXS9 (सेवारत कर्मियों की पत्नियां)": "EXS9 (Wives of Serving)"
}

sports_cat_options = ["None", "A (Absolute Priority)", "B", "C", "D", "E"] if not is_hindi else ["कोई नहीं", "A (सर्वोच्च प्राथमिकता)", "B", "C", "D", "E"]
sports_cat_map = {
    "None": "None", "कोई नहीं": "None",
    "A (Absolute Priority)": "A", "A (सर्वोच्च प्राथमिकता)": "A",
    "B": "B", "C": "C", "D": "D", "E": "E"
}

subject_list_en = [
    "Physics", "Mathematics", "Chemistry", "Computer Science", 
    "Electronics", "Information Technology", "Biology", 
    "Informatics Practices", "Biotechnology", "Technical Vocational subject", 
    "Agriculture", "Agriculture Stream", "Engineering Graphics", "Business Studies", "Entrepreneurship"
]

subject_translation = {
    "Physics": "भौतिक विज्ञान (Physics)",
    "Mathematics": "गणित (Mathematics)",
    "Chemistry": "रसायन विज्ञान (Chemistry)",
    "Computer Science": "कंप्यूटर विज्ञान (Computer Science)",
    "Electronics": "इलेक्ट्रॉनिक्स (Electronics)",
    "Information Technology": "सूचना प्रौद्योगिकी (Information Technology)",
    "Biology": "जीव विज्ञान (Biology)",
    "Informatics Practices": "इन्फॉर्मेटिक्स प्रैक्टिसेज (Informatics Practices)",
    "Biotechnology": "जैव प्रौद्योगिकी (Biotechnology)",
    "Technical Vocational subject": "तकनीकी व्यावसायिक विषय (Technical Vocational subject)",
    "Agriculture": "कृषि (Agriculture)",
    "Agriculture Stream": "कृषि स्ट्रीम (Agriculture Stream)",
    "Engineering Graphics": "इंजीनियरिंग ग्राफिक्स (Engineering Graphics)",
    "Business Studies": "बिजनेस स्टडीज (Business Studies)",
    "Entrepreneurship": "उद्यमिता (Entrepreneurship)"
}

if is_hindi:
    subject_display_list = [subject_translation[s] for s in subject_list_en]
    sub_display_to_en = {v: k for k, v in subject_translation.items()}
    sub_display_to_en["-- चुनें --"] = "-- Select --"
    select_placeholder = "-- चुनें --"
else:
    subject_display_list = subject_list_en
    sub_display_to_en = {s: s for s in subject_list_en}
    sub_display_to_en["-- Select --"] = "-- Select --"
    select_placeholder = "-- Select --"


# --- 4. OFFICIAL LOGO & HEADER STYLING ---
def get_base64_of_bin_file(bin_file):
    if os.path.exists(bin_file):
        with open(bin_file, 'rb') as f:
            data = f.read()
        return base64.b64encode(data).decode()
    return ""

logo_base64 = get_base64_of_bin_file("CEGLogo.png")
logo_html = f'<img src="data:image/png;base64,{logo_base64}" class="header-logo">' if logo_base64 else ''

st.markdown(f"""
<style>
    .official-header {{
        background: linear-gradient(135deg, #112240 0%, #0A192F 100%);
        padding: 20px 30px;
        border-radius: 12px;
        border-bottom: 4px solid #D4AF37; 
        display: flex;
        align-items: center; 
        justify-content: flex-start; 
        margin-bottom: 20px;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.4);
    }}
    .header-logo {{ height: 100px; margin-right: 30px; }}
    .header-text {{ display: flex; flex-direction: column; justify-content: center; }}
    .header-text h1 {{ font-family: 'Georgia', serif; font-weight: 800; margin: 0; margin-bottom: 5px; font-size: 2.6rem; color: #FFFFFF; line-height: 1.1; }}
    .header-text p {{ margin: 0; font-size: 1.1rem; letter-spacing: 1px; color: #e2e8f0; }}
    .highlight {{ color: #D4AF37; }}
    .stButton > button[kind="secondary"]:hover {{
        border-color: #EF4444; 
        color: #EF4444; 
    }}
</style>
<div class="official-header">
    {logo_html}
    <div class="header-text">
        <h1>{T["app_title"]} <span class="highlight">2026</span></h1>
        <p>{T["app_subtitle"]}</p>
    </div>
</div>
""", unsafe_allow_html=True)

st.warning(f"**{T['disclaimer_title']}** {T['disclaimer_text']}")


# --- 5. PDF GENERATION ENGINE ---
def generate_pdf_report(data):
    """Generates a professional, print-ready PDF summary of the simulation results."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    navy = (17, 34, 64)
    gold = (212, 175, 55)
    dark_gray = (55, 65, 81)
    light_gray = (243, 244, 246)
    
    # Header Banner
    pdf.set_fill_color(*navy)
    pdf.rect(0, 0, 210, 42, 'F')
    
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 24)
    pdf.set_y(10)
    pdf.cell(0, 10, 'REAP 2026', ln=True, align='C')
    
    pdf.set_text_color(*gold)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'CENTRALIZED ADMISSION PROCESS - ELIGIBILITY REPORT', ln=True, align='C')
    
    pdf.ln(22)
    
    # Document Title
    pdf.set_text_color(*navy)
    pdf.set_font('Helvetica', 'B', 15)
    pdf.cell(0, 10, 'TENTATIVE EVALUATION SUMMARY', ln=True)
    pdf.set_draw_color(*gold)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # Candidate details layout grid (using precise widths)
    pdf.set_text_color(*dark_gray)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(95, 7, 'CANDIDATE PROFILE', ln=False)
    pdf.cell(95, 7, 'ACADEMIC CREDENTIALS', ln=True)
    pdf.set_font('Helvetica', '', 10)
    
    # Row 1
    pdf.cell(40, 6, 'Name:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(55, 6, str(data.get('name', 'Anonymous')), ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(45, 6, 'Qualifying Exam:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, str(data.get('qual_exam', 'N/A')), ln=True)
    
    # Row 2
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(40, 6, 'Date of Birth:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(55, 6, str(data.get('dob', 'N/A')), ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(45, 6, 'Qualifying Percentage:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, f"{data.get('entered_perc', 0.0):.2f}%", ln=True)
    
    # Row 3
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(40, 6, 'Domicile State:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(55, 6, str(data.get('domicile', 'N/A')), ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(45, 6, 'JEE Mains Percentile:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, f"{data.get('jee_score', 0.0):.2f}", ln=True)
    
    # Row 4
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(40, 6, 'Category & Gender:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(55, 6, f"{data.get('category')} ({data.get('gender')})", ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(45, 6, '10th Board Marks:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, f"{data.get('perc_10th', 0.0):.2f}%", ln=True)
    
    pdf.ln(8)
    
    # Results Box Container
    pdf.set_fill_color(*light_gray)
    pdf.rect(10, pdf.get_y(), 190, 48, 'F')
    pdf.set_y(pdf.get_y() + 3)
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(*navy)
    pdf.cell(0, 7, '   SIMULATION EVALUATION RESULTS', ln=True)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(*dark_gray)
    
    pdf.cell(60, 6, '     Calculated Priority Tier:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, str(data.get('display_priority', 'N/A')), ln=True)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(60, 6, '     Final Seat Matrix Category:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, str(data.get('backend_category', 'N/A')), ln=True)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(60, 6, '     Effective Academic Score:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, f"{data.get('effective_score', 0.0):.2f}", ln=True)

    pdf.set_font('Helvetica', '', 10)
    pdf.cell(60, 6, '     Eligible AICTE Group(s):', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, ', '.join(data.get('eligible_groups', ['N/A'])), ln=True)
    
    pdf.set_y(pdf.get_y() + 10)
    
    # Ranks Section
    pdf.set_text_color(*navy)
    pdf.set_font('Helvetica', 'B', 13)
    pdf.cell(0, 8, 'PROJECTED TARGET RANKING COHORTS', ln=True)
    pdf.set_draw_color(*gold)
    pdf.set_line_width(0.4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(*dark_gray)
    pdf.multi_cell(0, 5, 'Based on the entered credentials, the candidate is dynamic assigned eligibility to compete in the following ranking lists (pools):', ln=True)
    pdf.ln(2)
    
    pdf.set_font('Helvetica', 'B', 10)
    for rank in data.get('ranks', []):
        clean_rank = rank.replace('🔹 ', '').strip()
        pdf.cell(10, 6, '  -', ln=False)
        pdf.cell(0, 6, clean_rank, ln=True)
        
    pdf.ln(8)
    
    # Warning Legal Disclaimer Frame
    pdf.set_fill_color(254, 243, 199) # soft amber box
    pdf.rect(10, pdf.get_y(), 190, 32, 'F')
    pdf.set_y(pdf.get_y() + 2)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_text_color(180, 83, 9) # amber title text
    pdf.cell(0, 4, '    OFFICIAL REAP-2026 SYSTEM DISCLAIMER:', ln=True)
    pdf.set_font('Helvetica', '', 7.5)
    pdf.multi_cell(180, 3.5, (
        "    This Eligibility Simulator is provided for informational and guidance purposes only. The projected priority tiers,\n"
        "    effective scores, and ranking lists generated by this tool are tentative and based entirely on the unverified data entered\n"
        "    by the user. The final, official merit list and ranks will be generated by the Centre for Electronic Governance during\n"
        "    the actual REAP-2026 Centralized Admission Process after thorough verification of original documents."
    ), align='L')
    
    return pdf.output()


# --- 6. INPUT LAYOUT (Dynamic & Reactive) ---
st.markdown(f"### {T['eval_details_header']}")

with st.expander(T["step1_title"], expanded=True):
    c1, c2, c3 = st.columns(3)
    with c1:
        name = st.text_input(T["cand_name"], "")
    with c2:
        dob = st.date_input(T["dob"], datetime(2005, 1, 1), help=T["dob_help"])
    with c3:
        perc_10th = st.number_input(T["perc_10th"], min_value=0.0, max_value=100.0, value=80.0, step=0.1, help=T["perc_10th_help"])

    st.markdown("---")
    
    c4, c5 = st.columns(2)
    with c4:
        selected_qual_exam = st.selectbox(T["qual_basis"], qual_exam_options)
        qual_exam = qual_exam_map[selected_qual_exam]
    
    with c5:
        is_jee_disabled = qual_exam in ["Diploma", "D.Voc"]
        jee_score = st.number_input(
            T["jee_score"], min_value=0.0, max_value=100.0, 
            value=0.0 if is_jee_disabled else 25.0, step=0.1, disabled=is_jee_disabled, 
            help=T["jee_help"]
        )

    perc_12th = 0.0
    perc_diploma = 0.0
    perc_dvoc = 0.0
    selected_subs = []
    
    if qual_exam == "Diploma":
        st.success(T["diploma_success"])
        perc_diploma = st.number_input(T["diploma_pct"], min_value=0.0, max_value=100.0, value=75.0, step=0.1, help=T["cutoff_help"])
        
    elif qual_exam == "D.Voc":
        st.info(T["dvoc_info"])
        perc_dvoc = st.number_input(T["dvoc_pct"], min_value=0.0, max_value=100.0, value=75.0, step=0.1, help=T["cutoff_help"])
        
    elif qual_exam == "12th Board":
        st.markdown(f"##### {T['subject_12_title']}")
        st.caption(T["subject_12_caption"])
        
        c_s1, c_s2, c_s3 = st.columns(3)
        
        selected_sub1 = c_s1.selectbox(T["sub1_label"], [select_placeholder] + subject_display_list)
        sub1 = sub_display_to_en[selected_sub1]
        
        sub2_options = [select_placeholder] + [s for s in subject_display_list if sub_display_to_en[s] != sub1 and sub_display_to_en[s] != "Agriculture Stream"]
        is_sub2_disabled = (sub1 == "-- Select --" or sub1 == "Agriculture Stream")
        selected_sub2 = c_s2.selectbox(T["sub2_label"], sub2_options, disabled=is_sub2_disabled)
        sub2 = sub_display_to_en[selected_sub2]
        
        sub3_options = [select_placeholder] + [s for s in subject_display_list if sub_display_to_en[s] not in [sub1, sub2] and sub_display_to_en[s] != "Agriculture Stream"]
        is_sub3_disabled = (sub2 == "-- Select --" or sub1 == "Agriculture Stream")
        selected_sub3 = c_s3.selectbox(T["sub3_label"], sub3_options, disabled=is_sub3_disabled)
        sub3 = sub_display_to_en[selected_sub3]
        
        if sub1 == "Agriculture Stream":
            selected_subs = [sub1]
        else:
            selected_subs = [s for s in [sub1, sub2, sub3] if s != "-- Select --"]
            
        perc_12th = st.number_input(T["perc_12th_label"], min_value=0.0, max_value=100.0, value=75.0, step=0.1, help=T["cutoff_help"])

with st.expander(T["step2_title"], expanded=True):
    c3, c4 = st.columns(2)
    with c3:
        sel_gender = st.selectbox(T["gender"], gender_options, help=T["gender_help"])
        gender = gender_map[sel_gender]
        
        sel_category = st.selectbox(T["base_cat"], category_options, help=T["base_cat_help"])
        category = category_map[sel_category]
    with c4:
        sel_area = st.selectbox(T["area"], area_options, help=T["area_help"])
        area = area_map[sel_area]
        
        sel_domicile = st.selectbox(T["domicile"], domicile_options, help=T["domicile_help"])
        domicile = domicile_map[sel_domicile]

with st.expander(T["step3_title"], expanded=False):
    c5, c6 = st.columns(2)
    with c5:
        pwd_quota = st.checkbox(T["pwd_label"], help=T["pwd_help"])
        income_less_8l = st.checkbox(T["tfws_label"], help=T["tfws_help"])
        km_quota = st.checkbox(T["km_label"], help=T["km_help"])
        wp_quota = st.checkbox(T["wp_label"], help=T["wp_help"])
        fn_quota = st.checkbox(T["fn_label"], help=T["fn_help"])
    with c6:
        sel_exs = st.selectbox(T["exs_label"], exs_options, help=T["exs_help"])
        exs_priority = exs_map[sel_exs]

        sports_quota = st.checkbox(T["sports_label"], help=T["sports_cat_help"])
        sel_sports_cat = st.selectbox(T["sports_cat_label"], sports_cat_options, help=T["sports_cat_help"])
        sports_cat = sports_cat_map[sel_sports_cat]

st.markdown("<br>", unsafe_allow_html=True)
submit_btn_col1, submit_btn_col2, submit_btn_col3 = st.columns([1, 1, 1])
with submit_btn_col2:
    submitted = st.button(T["submit_btn"], type="secondary", use_container_width=True)


# --- 7. ALGORITHM EXECUTION & DASHBOARD ---
if submitted:
    st.toast(T["toast_done"], icon="✅")
    st.divider()

    if qual_exam == "-- Select --":
        st.error(T["err_qual_exam"])
        st.stop()

    st.markdown(f"## {T['dashboard_title']}")

    # --- ELIGIBILITY & GROUP MESSAGES ---
    eligible_groups = []
    
    if qual_exam == "12th Board":
        if sub1 == "Agriculture Stream":
            eligible_groups.append("Group-5 Branches")
        else:
            if len(selected_subs) < 3:
                st.error(T["err_3_subjects"])
                st.stop()
            
            subs_set = set(selected_subs)
            if {"Physics", "Chemistry", "Mathematics"}.issubset(subs_set):
                eligible_groups.append("Group-1 (All Branches)")
            else:
                if {"Physics", "Mathematics"}.issubset(subs_set):
                    eligible_groups.append("Group-2 Branches")
                if {"Physics", "Chemistry"}.issubset(subs_set):
                    eligible_groups.append("Group-4 Branches")
                if "Mathematics" in subs_set and not {"Physics", "Mathematics"}.issubset(subs_set):
                    eligible_groups.append("Group-6 Branches")
                if "Chemistry" in subs_set and not {"Physics", "Chemistry"}.issubset(subs_set):
                    eligible_groups.append("Group-3 Branches")
                if "Agriculture" in subs_set:
                    eligible_groups.append("Group-5 Branches")
                    
        if eligible_groups:
            st.success(f"{T['group_eligible_msg']} **{', '.join(eligible_groups)}**")
            
            with st.expander("📄 Click here for details / विवरण के लिए यहां क्लिक करें", expanded=False):
                st.markdown("""
                **AICTE Eligibility Groups for 12th Board Candidates:**
                * **Group 1:** Physics, Chemistry, Maths
                * **Group 2:** Physics, Maths, one additional subject
                * **Group 3:** Chemistry, two additional subjects
                * **Group 4:** Physics, Chemistry, one additional subject
                * **Group 5:** Agriculture Stream
                * **Group 6:** Maths, two additional subjects
                """)
                
                if os.path.exists("Group_Branches.pdf"):
                    with open("Group_Branches.pdf", "rb") as pdf_file:
                        pdf_b64 = base64.b64encode(pdf_file.read()).decode()
                        button_html = f'''
                        <a href="data:application/pdf;base64,{pdf_b64}" download="Group_Branches.pdf" style="display: inline-block; padding: 0.5rem 1rem; color: #FFFFFF; background-color: #112240; border: 1px solid #D4AF37; border-radius: 6px; text-decoration: none; font-weight: 600; text-align: center; margin-top: 10px;">
                            📥 Download Detailed AICTE Mapping
                        </a>
                        '''
                        st.markdown(button_html, unsafe_allow_html=True)
        else:
            st.error(T["disq_aicte"])
            st.stop()

    # --- DOMICILE & RESERVATION OVERRIDE LOGIC ---
    backend_category = category
    km_override_applied = False
    dom_override_applied = False
    res_override_applied = False

    if km_quota:
        domicile = "Outside Rajasthan"
        backend_category = "GEN"
        km_override_applied = True

    if domicile != "Rajasthan":
        if backend_category != "GEN":
            backend_category = "GEN"
            dom_override_applied = True

        pwd_quota = False
        exs_priority = "None"
        area = "Non-TSP"
        sports_quota = False

    entered_perc = 0.0
    if qual_exam == "12th Board":
        entered_perc = perc_12th
    elif qual_exam == "Diploma":
        entered_perc = perc_diploma
        jee_score = 0.0 
    elif qual_exam == "D.Voc":
        entered_perc = perc_dvoc
        jee_score = 0.0

    req_cutoff = 45.0 if backend_category == "GEN" else 40.0
    is_eligible_marks = entered_perc >= req_cutoff

    # --- CLEAN DISQUALIFICATION LOGIC ---
    if not is_eligible_marks:
        cat_text = "Kashmiri Migrant" if km_override_applied else backend_category
        st.error(f"{T['disq_cutoff']}\n\n{cat_text} {T['require_marks']} {req_cutoff}% in {qual_exam}. {T['scored_marks']}: {entered_perc}%.")

    else:
        jee_basis = (jee_score >= 20.0 and qual_exam == "12th Board")

        # Assign Priorities cleanly
        if jee_basis:
            academic_priority = "Priority 2 (JEE Mains)"
            base_score = jee_score
        elif qual_exam == "12th Board":
            academic_priority = "Priority 3 (12th Board)"
            base_score = entered_perc
        elif qual_exam == "Diploma":
            academic_priority = "Priority 3 (Diploma)"
            base_score = entered_perc
        elif qual_exam == "D.Voc":
            academic_priority = "Priority 4 (D.Voc)"
            base_score = entered_perc

        # Automated Sports Weightage & Priority A Logic
        effective_score = base_score
        sports_bonus_applied = False
        sports_weight = 0.0
        is_category_a = False
        cat_letter = "None"

        if domicile == "Rajasthan" and sports_quota and sports_cat != "None" and not wp_quota and not fn_quota:
            cat_letter = sports_cat
            if cat_letter == "A":
                is_category_a = True
                sports_weight = 7.0
            elif cat_letter == "B":
                sports_weight = 7.0
            elif cat_letter == "C":
                sports_weight = 5.0
            elif cat_letter == "D":
                sports_weight = 4.0
            elif cat_letter == "E":
                sports_weight = 2.0

            effective_score += sports_weight
            sports_bonus_applied = True

        display_priority = "Priority 1 (Sports A)" if is_category_a else academic_priority

        # --- DASHBOARD LAYOUT WITH SPEEDOMETER ---
        dash_col1, dash_col2 = st.columns([1.5, 1])

        with dash_col1:
            mc1, mc2 = st.columns(2)
            mc1.metric(
                label=T["priority_metric"], value=display_priority,
                delta=T["highest_eligible_delta"] if jee_basis else None
            )

            mc2.metric(
                label=T["matrix_metric"], value=backend_category,
                delta=T["outofstate_delta"] if (dom_override_applied and not wp_quota and not fn_quota) else None, delta_color="off"
            )

            if is_category_a:
                st.info(T["sports_fallback_msg"].format(academic_priority=academic_priority, effective_score=effective_score))

            if km_override_applied:
                st.warning(T["km_rule_warning"])
            elif domicile != "Rajasthan" and not wp_quota and not fn_quota:
                st.warning(T["out_of_state_warning"])

            st.markdown(f"### {T['projected_lists_title']}")

            # EXCLUSIVE POOL OVERRIDES
            if wp_quota:
                st.error(T["wp_exclusive_error"])
                ranks = ["🔹 `mwp` (Working Professional Supernumerary Quota)"]
                st.success(T["tiebreaker_seq_msg"])
                st.info("\n".join(ranks))

            elif fn_quota:
                st.error(T["fn_exclusive_error"])
                ranks = ["🔹 `mfn` (Foreign National/OCI/Gulf Quota - 15% Supernumerary)"]
                st.success(T["tiebreaker_seq_msg"])
                st.info("\n".join(ranks))

            else:
                ranks = []
                if domicile == "Rajasthan":
                    ranks.append("🔹 `mmerit` (Overall State Merit)")
                    if gender == "F": ranks.append("🔹 `mgenf` (Overall General Female)")

                    if backend_category in ["OBC (Non-Creamy)", "OBC", "SC", "ST", "MBC (Non-Creamy)", "MBC", "EWS"]:
                        clean_cat_prefix = backend_category.split(" ")[0].lower()
                        ranks.append(f"🔹 `m{clean_cat_prefix}` (Category {backend_category})")
                        if gender == "F": ranks.append(f"🔹 `m{clean_cat_prefix}f` (Category {backend_category} Female)")

                    if backend_category == "ST" and area == "TSP":
                        ranks.append("🔹 `mtsp` (TSP Quota - 45% of ST Reserved)")
                        if gender == "F": ranks.append("🔹 `mtspf` (TSP Female Quota)")

                    if pwd_quota:
                        ranks.append("🔹 `mpwd` (Persons with Special Ability - 5% Horizontal)")
                        if gender == "F": ranks.append("🔹 `mpwdf` (PwD Female)")

                    if exs_priority != "None":
                        tier_num = exs_priority.split(" ")[0]
                        ranks.append(f"🔹 `mexs` (Ex-Servicemen Priority Sort - Tier {tier_num})")
                        if gender == "F": ranks.append("🔹 `mexsf` (Ex-Servicemen Female)")

                    if sports_quota and sports_cat != "None":
                        if cat_letter == "A":
                            ranks.append(f"🔹 `msqa` (Priority 1: Sports Category A - Max 5% capacity, then falls back to Sports Category B)")
                        else:
                            ranks.append(f"🔹 `msqa` (Sports Priority Sort - Category {cat_letter})")
                else:
                    ranks.append("🔹 `mor` (Outside Rajasthan Quota - 15%) - **Eligible for Self Financed Seats (SFS) ONLY**")

                if km_quota:
                    ranks.append("🔹 `mkm` (Kashmiri Migrant Supernumerary Quota - 5%)")
                    if gender == "F": ranks.append("🔹 `mkmf` (Kashmiri Migrant Female)")
                if income_less_8l: ranks.append("🔹 `mtfw` (Tuition Fee Waiver Scheme Supernumerary - 5%)")

                st.success(T["tiebreaker_seq_msg"])
                st.info("\n".join(ranks))

            # --- DYNAMIC REPORT GENERATION BUTTON ---
            st.write("")
            if FPDF_AVAILABLE:
                pdf_payload = {
                    'name': name if name.strip() else ("Candidate" if not is_hindi else "अभ्यर्थी"),
                    'dob': dob.strftime('%d-%m-%Y'),
                    'perc_10th': perc_10th,
                    'qual_exam': qual_exam,
                    'entered_perc': entered_perc,
                    'jee_score': jee_score,
                    'category': backend_category,
                    'gender': gender,
                    'domicile': domicile,
                    'display_priority': display_priority,
                    'backend_category': backend_category,
                    'effective_score': effective_score,
                    'eligible_groups': eligible_groups if eligible_groups else ["Diploma Equivalent (Group 1)"],
                    'ranks': ranks
                }
                
                try:
                    pdf_data = generate_pdf_report(pdf_payload)
                    st.download_button(
                        label=T["download_report_btn"],
                        data=pdf_data,
                        file_name=f"REAP_2026_Eligibility_Report_{pdf_payload['name'].replace(' ', '_')}.pdf",
                        mime="application/pdf",
                        use_container_width=True
                    )
                except Exception as e:
                    st.error(f"Error compiling PDF: {e}")
            else:
                st.info(T["pdf_install_helper"])

        with dash_col2:
            fig = go.Figure(go.Indicator(
                mode="gauge+number+delta",
                value=effective_score,
                domain={'x': [0, 1], 'y': [0, 1]},
                title={'text': T["eff_academic_score"], 'font': {'size': 22}},
                delta={'reference': base_score, 'increasing': {'color': "#10B981"}, 'position': "top"},
                gauge={
                    'axis': {'range': [None, 120], 'tickwidth': 1},
                    'bar': {'color': "#D4AF37", 'thickness': 0.75},
                    'bgcolor': "rgba(0,0,0,0)",
                    'borderwidth': 2,
                    'bordercolor': "gray",
                    'steps': [
                        {'range': [0, req_cutoff], 'color': "rgba(239, 68, 68, 0.4)"},
                        {'range': [req_cutoff, 75], 'color': "rgba(245, 158, 11, 0.3)"},
                        {'range': [75, 120], 'color': "rgba(16, 185, 129, 0.3)"}],
                    'threshold': {
                        'line': {'color': "gray", 'width': 4},
                        'thickness': 0.75,
                        'value': effective_score}
                }
            ))

            fig.update_layout(
                paper_bgcolor="rgba(0,0,0,0)",
                height=350,
                margin=dict(l=20, r=20, t=50, b=20)
            )

            st.plotly_chart(fig, use_container_width=True, theme="streamlit")

            if sports_bonus_applied:
                st.caption(T["sports_bonus_caption"].format(sports_weight=sports_weight, cat_letter=cat_letter))
            else:
                st.caption(T["pure_academic_caption"])
