import streamlit as st
import pandas as pd
import time
from datetime import datetime
import os
import base64
import plotly.graph_objects as go

# --- 1. UI CONFIGURATION & THEME ---
st.set_page_config(page_title="REAP-2026 Eligibility Simulator", page_icon="🏛️", layout="wide")


def get_base64_of_bin_file(bin_file):
    if os.path.exists(bin_file):
        with open(bin_file, 'rb') as f:
            data = f.read()
        return base64.b64encode(data).decode()
    return ""


logo_base64 = get_base64_of_bin_file("CEGLogo.png")
logo_html = f'<img src="data:image/png;base64,{logo_base64}" class="header-logo">' if logo_base64 else ''

# Official Header CSS 
st.markdown(f"""
<style>
    .official-header {{
        background: linear-gradient(135deg, #112240 0%, #0A192F 100%);
        padding: 20px 30px;
        border-radius: 12px;
        border-bottom: 4px solid #D4AF37; 
        display: flex;
        align-items: center; 
        justify-content: flex-start; 
        margin-bottom: 20px;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.4);
    }}
    .header-logo {{ height: 100px; margin-right: 30px; }}
    .header-text {{ display: flex; flex-direction: column; justify-content: center; }}
    .header-text h1 {{ font-family: 'Georgia', serif; font-weight: 800; margin: 0; margin-bottom: 5px; font-size: 2.6rem; color: #FFFFFF; line-height: 1.1; }}
    .header-text p {{ margin: 0; font-size: 1.1rem; letter-spacing: 1px; color: #e2e8f0; }}
    .highlight {{ color: #D4AF37; }}

    .stButton > button[kind="secondary"]:hover {{
        border-color: #EF4444; 
        color: #EF4444; 
    }}
</style>
<div class="official-header">
    {logo_html}
    <div class="header-text">
        <h1>REAP <span class="highlight">2026</span></h1>
        <p>CENTRALIZED ADMISSION PROCESS • ELIGIBILITY SIMULATOR</p>
    </div>
</div>
""", unsafe_allow_html=True)

st.warning(
    "**OFFICIAL DISCLAIMER:** This Eligibility Simulator is provided for informational and guidance purposes only. The projected priority tiers, effective scores, and ranking lists generated by this tool are tentative and based entirely on the unverified data entered by the user. The final, official merit list and ranks will be generated by the Centre for Electronic Governance during the actual REAP-2026 Centralized Admission Process after thorough verification of original documents.")

# --- 2. INPUT LAYOUT (Dynamic & Reactive) ---
st.markdown("### 📋 Candidate Evaluation Details")

with st.expander("🎓 Step 1: Academic Information", expanded=True):
    c1, c2 = st.columns(2)
    with c1:
        name = st.text_input("Candidate Name", "")
        jee_score = st.number_input("JEE Percentile (0 if none)", min_value=0.0, max_value=100.0, value=25.0,
                                    step=0.1, help="Rank obtained in JEE (Mains) 2026. Evaluated as Priority 2. Requires a minimum of 20 percentile.")
    with c2:
        dob = st.date_input("Date of Birth", datetime(2005, 1, 1),
                            help="Used as the final tie-breaker. Older candidates rank higher.")
        perc_10th = st.number_input("10th Board (%)", min_value=0.0, max_value=100.0, value=80.0, step=0.1,
                                    help="Used internally as a secondary tie-breaker if Effective Score and Qualifying % are identical.")

    st.markdown("---")
    qual_exam = st.selectbox("Select Qualifying Basis", ["-- Select --", "12th Board", "Diploma", "D.Voc"])
    
    perc_12th = 0.0
    perc_diploma = 0.0
    perc_dvoc = 0.0
    selected_subs = []
    
    if qual_exam == "Diploma":
        perc_diploma = st.number_input("Diploma (%)", min_value=0.0, max_value=100.0, value=75.0, step=0.1, help="Eligibility cutoff is 45% for GEN and 40% for Reserved categories.")
        
    elif qual_exam == "D.Voc":
        perc_dvoc = st.number_input("D.Voc (%)", min_value=0.0, max_value=100.0, value=75.0, step=0.1, help="Eligibility cutoff is 45% for GEN and 40% for Reserved categories.")
        
    elif qual_exam == "12th Board":
        st.markdown("##### Select 12th Board Subjects (Choose 3 Mandatory Subjects)")
        subject_list = [
            "Physics", "Mathematics", "Chemistry", "Computer Science", 
            "Electronics", "Information Technology", "Biology", 
            "Informatics Practices", "Biotechnology", "Technical Vocational subject", 
            "Agriculture", "Agriculture Stream", "Engineering Graphics", "Business Studies", "Entrepreneurship"
        ]
        
        c_s1, c_s2, c_s3 = st.columns(3)
        
        # Subject 1 (Always Active)
        sub1 = c_s1.selectbox("Subject 1", ["-- Select --"] + subject_list)
        
        # Subject 2 (Active only if Sub 1 is selected, Options exclude Sub 1)
        sub2_options = ["-- Select --"] + [s for s in subject_list if s != sub1]
        is_sub2_disabled = (sub1 == "-- Select --" or sub1 == "Agriculture Stream")
        sub2 = c_s2.selectbox("Subject 2", sub2_options, disabled=is_sub2_disabled)
        
        # Subject 3 (Active only if Sub 2 is selected, Options exclude Sub 1 & Sub 2)
        sub3_options = ["-- Select --"] + [s for s in subject_list if s not in [sub1, sub2]]
        is_sub3_disabled = (sub2 == "-- Select --" or sub1 == "Agriculture Stream")
        sub3 = c_s3.selectbox("Subject 3", sub3_options, disabled=is_sub3_disabled)
        
        # Populate selected_subs based on Agriculture Stream exception
        if sub1 == "Agriculture Stream":
            selected_subs = [sub1]
        else:
            selected_subs = [s for s in [sub1, sub2, sub3] if s != "-- Select --"]
            
        perc_12th = st.number_input("12th Board (%)", min_value=0.0, max_value=100.0, value=75.0, step=0.1, help="Eligibility cutoff is 45% for GEN and 40% for Reserved categories.")

with st.expander("🌍 Step 2: Demographics & Base Category", expanded=True):
    c3, c4 = st.columns(2)
    with c3:
        gender = st.selectbox("Gender", ["M", "F", "Other"],
                              help="Female candidates receive a 30% horizontal reservation across all categories (Rajasthan Domicile Only).")
        category = st.selectbox("Base Category", ["GEN", "OBC (Non-Creamy)", "SC", "ST", "MBC (Non-Creamy)", "EWS"],
                                help="Determines your vertical reservation quota in the State Matrix.")
    with c4:
        area = st.selectbox("Area Type", ["Non-TSP", "TSP"],
                            help="Tribal Sub Plan (TSP) area. 45% of the ST quota is horizontally reserved for TSP candidates. Only applicable if Category is ST.")
        domicile = st.selectbox("Domicile", ["Rajasthan", "Outside Rajasthan"],
                                help="Non-Rajasthan candidates are strictly processed as UR/GEN with NO horizontal reservations and are only eligible for Self Financed Seats (SFS).")

with st.expander("⭐ Step 3: Supernumerary and Other Quotas", expanded=False):
    c5, c6 = st.columns(2)
    with c5:
        pwd_quota = st.checkbox("Person with Special Ability (PwD)",
                                help="Grants a 5% horizontal reservation (Rajasthan Domicile Only).")
        income_less_8l = st.checkbox("Income < ₹8.00 Lakhs (TFWS)",
                                     help="Determines eligibility for the Tuition Fee Waiver Scheme (TFWS), which comprises up to 5% supernumerary seats.")
        km_quota = st.checkbox("Kashmiri Migrant (KM)",
                               help="5% additional supernumerary seats for Kashmiri Pandits/Hindu Families. Processed internally as Outside Rajasthan + GEN.")
        wp_quota = st.checkbox("Working Professional (WP)",
                               help="Exclusive supernumerary seats for candidates with 2+ years experience and workplace within 80km. Removes candidate from the main admission pool.")
        fn_quota = st.checkbox("Foreign National / OCI / Gulf",
                               help="15% supernumerary seats over approved intake for Foreign Nationals and Children of Indian workers in Gulf countries. Removed from main admission pool.")
    with c6:
        exs_priority = st.selectbox("Ex-Servicemen (EXS)", [
            "None", "EXS1 (Killed in action)", "EXS2 (Disabled in action)", "EXS3 (Died in service)",
            "EXS4 (Disabled in service)", "EXS5 (Gallantry Awards)", "EXS6 (Wards of EXS)",
            "EXS7 (Wives of EXS)", "EXS8 (Wards of Serving)", "EXS9 (Wives of Serving)"
        ], help="3% horizontal reservation for dependents of Defence personnel (Rajasthan Domicile Only).")

        sports_quota = st.checkbox("Valid Sports Quota", help="Only available for Rajasthan Domicile candidates.")
        sports_cat = st.selectbox("Sports Category", ["None", "A (Absolute Priority)", "B", "C", "D", "E"],
                                  help="System automatically applies weightage: A/B (+7), C (+5), D (+4), E (+2). Category A has max 5% seat capacity before falling back to B.")

st.markdown("<br>", unsafe_allow_html=True)
submit_btn_col1, submit_btn_col2, submit_btn_col3 = st.columns([1, 1, 1])
with submit_btn_col2:
    submitted = st.button("🚀 Run Eligibility Simulator", type="secondary", use_container_width=True)

# --- 3. ALGORITHM EXECUTION & DASHBOARD ---
if submitted:
    st.toast("Eligibility Calculation Completed!", icon="✅")
    st.divider()

    if qual_exam == "-- Select --":
        st.error("⚠️ **Action Required:** Please select a Qualifying Basis (12th Board, Diploma, or D.Voc) in Step 1 to proceed.")
        st.stop()

    st.markdown("## 📊 Candidate Eligibility Dashboard")

    # --- ELIGIBILITY & GROUP MESSAGES ---
    eligible_groups = []
    
    if qual_exam == "12th Board":
        if sub1 == "Agriculture Stream":
            eligible_groups.append("Group-5 Branches")
        else:
            if len(selected_subs) < 3:
                st.error("❌ **Action Required:** Please select exactly three subjects from the 12th Board dropdowns in Step 1.")
                st.stop()
            
            subs_set = set(selected_subs)
            # AICTE Group Matching Logic
            if {"Physics", "Chemistry", "Mathematics"}.issubset(subs_set):
                eligible_groups.append("Group-1 (All Branches)")
            else:
                if {"Physics", "Mathematics"}.issubset(subs_set):
                    eligible_groups.append("Group-2 Branches")
                if {"Physics", "Chemistry"}.issubset(subs_set):
                    eligible_groups.append("Group-4 Branches")
                if "Mathematics" in subs_set and not {"Physics", "Mathematics"}.issubset(subs_set):
                    eligible_groups.append("Group-6 Branches")
                if "Chemistry" in subs_set and not {"Physics", "Chemistry"}.issubset(subs_set):
                    eligible_groups.append("Group-3 Branches")
                if "Agriculture" in subs_set:
                    eligible_groups.append("Group-5 Branches")
                    
        if eligible_groups:
            st.success(f"✅ Based on your 12th Board subjects, you are eligible for: **{', '.join(eligible_groups)}**")
            
            with st.expander("📄 Click here for more", expanded=False):
                st.markdown("""
                **AICTE Eligibility Groups for 12th Board Candidates:**
                * **Group 1:** Physics, Chemistry, Maths
                * **Group 2:** Physics, Maths, one additional subject
                * **Group 3:** Chemistry, two additional subjects
                * **Group 4:** Physics, Chemistry, one additional subject
                * **Group 5:** Agriculture Stream
                * **Group 6:** Maths, two additional subjects
                """)
                
                # Native HTML fallback button for form safety
                if os.path.exists("Group_Branches.pdf"):
                    with open("Group_Branches.pdf", "rb") as pdf_file:
                        pdf_b64 = base64.b64encode(pdf_file.read()).decode()
                        button_html = f'''
                        <a href="data:application/pdf;base64,{pdf_b64}" download="Group_Branches.pdf" style="display: inline-block; padding: 0.5rem 1rem; color: #FFFFFF; background-color: #112240; border: 1px solid #D4AF37; border-radius: 6px; text-decoration: none; font-weight: 600; text-align: center; margin-top: 10px;">
                            📥 Download to know in detail
                        </a>
                        '''
                        st.markdown(button_html, unsafe_allow_html=True)
        else:
            st.error("❌ Disqualified: This subject combination does not meet AICTE eligibility for any B.Tech/B.E. group.")
            st.stop()

    elif qual_exam == "Diploma":
        st.success("✅ **Note:** As a Diploma holder, you are considered equivalent to PCM. You are eligible for **Group-1 (All Branches)** and evaluated under **Priority 3**.")
        
    elif qual_exam == "D.Voc":
        st.info("📌 **Note:** You are eligible for the relevant branch in which you have passed the D.Voc. Evaluated under **Priority 4**.")


    # --- DOMICILE & RESERVATION OVERRIDE LOGIC ---
    backend_category = category.split(" ")[0]
    km_override_applied = False
    dom_override_applied = False
    res_override_applied = False

    if km_quota:
        domicile = "Outside Rajasthan"
        backend_category = "GEN"
        km_override_applied = True

    if domicile != "Rajasthan":
        if backend_category != "GEN":
            backend_category = "GEN"
            dom_override_applied = True

        # Nullify all horizontal reservations for Out of State candidates
        if pwd_quota or exs_priority != "None" or area == "TSP" or sports_quota:
            res_override_applied = True

        pwd_quota = False
        exs_priority = "None"
        area = "Non-TSP"
        sports_quota = False

    # Collect the specific percentage tied to the selected qualifying exam
    entered_perc = 0.0
    if qual_exam == "12th Board":
        entered_perc = perc_12th
    elif qual_exam == "Diploma":
        entered_perc = perc_diploma
    elif qual_exam == "D.Voc":
        entered_perc = perc_dvoc

    req_cutoff = 45.0 if backend_category == "GEN" else 40.0
    is_eligible_marks = entered_perc >= req_cutoff

    # --- CLEAN DISQUALIFICATION LOGIC ---
    if not is_eligible_marks:
        cat_text = "Kashmiri Migrant" if km_override_applied else backend_category
        st.error(f"### ❌ Disqualified: Failed Eligibility Criteria\n{cat_text} Candidate requires {req_cutoff}% in {qual_exam}. Candidate scored in {qual_exam}: {entered_perc}%.")

    else:
        jee_basis = jee_score >= 20.0

        # Assign Priorities cleanly
        if jee_basis:
            academic_priority = "Priority 2 (JEE)"
            base_score = jee_score
        elif qual_exam == "12th Board":
            academic_priority = "Priority 3 (12th Board)"
            base_score = entered_perc
        elif qual_exam == "Diploma":
            academic_priority = "Priority 3 (Diploma)"
            base_score = entered_perc
        elif qual_exam == "D.Voc":
            academic_priority = "Priority 4 (D.Voc)"
            base_score = entered_perc

        # Automated Sports Weightage & Priority A Logic
        effective_score = base_score
        sports_bonus_applied = False
        sports_weight = 0.0
        is_category_a = False
        cat_letter = "None"

        if domicile == "Rajasthan" and sports_quota and sports_cat != "None" and not wp_quota and not fn_quota:
            cat_letter = sports_cat.split(" ")[0]
            if cat_letter == "A":
                is_category_a = True
                sports_weight = 7.0
            elif cat_letter == "B":
                sports_weight = 7.0
            elif cat_letter == "C":
                sports_weight = 5.0
            elif cat_letter == "D":
                sports_weight = 4.0
            elif cat_letter == "E":
                sports_weight = 2.0

            effective_score += sports_weight
            sports_bonus_applied = True

        display_priority = "Priority 1 (Sports A)" if is_category_a else academic_priority

        # --- DASHBOARD LAYOUT WITH SPEEDOMETER ---
        dash_col1, dash_col2 = st.columns([1.5, 1])

        with dash_col1:
            mc1, mc2 = st.columns(2)
            mc1.metric(label="Calculated Priority Tier", value=display_priority,
                       delta="Highest Eligible" if jee_basis else None)

            mc2.metric(label="Final Matrix Category", value=backend_category,
                       delta="Out-of-State Override" if (dom_override_applied and not wp_quota and not fn_quota) else None, delta_color="off")

            if is_category_a:
                st.info(
                    f"**Note:** Priority 1 is capped at 5% of total course seats. If candidate does not secure a Priority 1 seat, he/she will fall back to **{academic_priority}** with an Effective Academic Score of {effective_score:.2f} (Adding +7.0).")

            if km_override_applied:
                st.warning(
                    "⚠️ **Kashmiri Migrant Rule Applied:** For main state matrix processing, Domicile is forced to 'Outside Rajasthan' and Category forced to 'GEN'.")
            elif domicile != "Rajasthan" and not wp_quota and not fn_quota:
                st.warning(
                    "⚠️ **Out-of-State Rule Applied:** Candidate is not a domicile of Rajasthan. Vertical/horizontal reservations are nullified, and the candidate is **excluded from the main State Merit (`mmerit`)**. The candidate is eligible **ONLY for Self Financed Seats (SFS)** under the Outside Rajasthan Quota.")

            st.markdown("### 🏆 Projected Ranking Lists")

            # EXCLUSIVE POOL OVERRIDES
            if wp_quota:
                st.error(
                    "🛑 **WORKING PROFESSIONAL EXCLUSIVE POOL**\n\nAs per AICTE norms, the candidate is removed from the main admission pool and placed exclusively in the Working Professionals list (`mwp`). No other state or horizontal reservations apply.")
                ranks = ["🔹 `mwp` (Working Professional Supernumerary Quota)"]
                st.success("Based on master tie-breaker logic, candidate will be positioned in the following sequence:")
                st.info("\n".join(ranks))

            elif fn_quota:
                st.error(
                    "🛑 **FOREIGN NATIONAL / GULF EXCLUSIVE POOL**\n\nAs per AICTE norms, the candidate is placed exclusively in the Foreign National list (`mfn`). No state vertical or horizontal reservations apply.")
                ranks = ["🔹 `mfn` (Foreign National/OCI/Gulf Quota - 15% Supernumerary)"]
                st.success("Based on master tie-breaker logic, candidate will be positioned in the following sequence:")
                st.info("\n".join(ranks))

            else:
                ranks = []
                if domicile == "Rajasthan":
                    ranks.append("🔹 `mmerit` (Overall State Merit)")
                    if gender == "F": ranks.append("🔹 `mgenf` (Overall General Female)")

                    if backend_category in ["OBC", "SC", "ST", "MBC", "EWS"]:
                        ranks.append(f"🔹 `m{backend_category.lower()}` (Category {backend_category})")
                        if gender == "F": ranks.append(
                            f"🔹 `m{backend_category.lower()}f` (Category {backend_category} Female)")

                    if backend_category == "ST" and area == "TSP":
                        ranks.append("🔹 `mtsp` (TSP Quota - 45% of ST Reserved)")
                        if gender == "F": ranks.append("🔹 `mtspf` (TSP Female Quota)")

                    if pwd_quota:
                        ranks.append("🔹 `mpwd` (Persons with Special Ability - 5% Horizontal)")
                        if gender == "F": ranks.append("🔹 `mpwdf` (PwD Female)")

                    if exs_priority != "None":
                        tier_num = exs_priority.split(" ")[0]
                        ranks.append(f"🔹 `mexs` (Ex-Servicemen Priority Sort - Tier {tier_num})")
                        if gender == "F": ranks.append("🔹 `mexsf` (Ex-Servicemen Female)")

                    if sports_quota and sports_cat != "None":
                        if cat_letter == "A":
                            ranks.append(
                                f"🔹 `msqa` (Priority 1: Sports Category A - Max 5% capacity, then falls back to Sports Category B)")
                        else:
                            ranks.append(f"🔹 `msqa` (Sports Priority Sort - Category {cat_letter})")
                else:
                    ranks.append(
                        "🔹 `mor` (Outside Rajasthan Quota - 15%) - **Eligible for Self Financed Seats (SFS) ONLY**")

                if km_quota:
                    ranks.append("🔹 `mkm` (Kashmiri Migrant Supernumerary Quota - 5%)")
                    if gender == "F": ranks.append("🔹 `mkmf` (Kashmiri Migrant Female)")
                if income_less_8l: ranks.append("🔹 `mtfw` (Tuition Fee Waiver Scheme Supernumerary - 5%)")

                st.success(
                    "Based on master tie-breaker logic, candidate will be positioned in the following sequences:")
                st.info("\n".join(ranks))

        with dash_col2:
            fig = go.Figure(go.Indicator(
                mode="gauge+number+delta",
                value=effective_score,
                domain={'x': [0, 1], 'y': [0, 1]},
                title={'text': "Effective Academic Score", 'font': {'size': 22}},
                delta={'reference': base_score, 'increasing': {'color': "#10B981"}, 'position': "top"},
                gauge={
                    'axis': {'range': [None, 120], 'tickwidth': 1},
                    'bar': {'color': "#D4AF37", 'thickness': 0.75},
                    'bgcolor': "rgba(0,0,0,0)",
                    'borderwidth': 2,
                    'bordercolor': "gray",
                    'steps': [
                        {'range': [0, req_cutoff], 'color': "rgba(239, 68, 68, 0.4)"},
                        {'range': [req_cutoff, 75], 'color': "rgba(245, 158, 11, 0.3)"},
                        {'range': [75, 120], 'color': "rgba(16, 185, 129, 0.3)"}],
                    'threshold': {
                        'line': {'color': "gray", 'width': 4},
                        'thickness': 0.75,
                        'value': effective_score}
                }
            ))

            fig.update_layout(
                paper_bgcolor="rgba(0,0,0,0)",
                height=350,
                margin=dict(l=20, r=20, t=50, b=20)
            )

            st.plotly_chart(fig, use_container_width=True, theme="streamlit")

            if sports_bonus_applied:
                st.caption(f"✨ Score includes **+{sports_weight} points** for Sports Quota Category {cat_letter}.")
            else:
                st.caption("Score based purely on academic priority tier.")
